# Semana 4 — Taller práctico: funciones, modularización y GitHub

**Asignatura:** Análisis de Datos con Python  
**Tipo de evidencia:** Notebook con ejercicios resueltos + repositorio inicial en GitHub  

## Propósito del taller

Aplicar funciones, modularización básica, comprensión de listas y diccionarios, manejo de errores y buenas prácticas de programación en un caso sencillo de análisis de datos.

## Entregables

1. Notebook completo con los ejercicios resueltos.
2. Repositorio inicial en GitHub con estructura organizada.
3. Archivo `README.md` con descripción del repositorio.
4. Evidencia del enlace al repositorio en la última sección del notebook.

## Instrucciones

Complete las celdas marcadas con `TODO`.

In [1]:
# Cargue y observe aquí los datos.
import pandas as pd

df = pd.read_csv("mecatronics_dataset.csv")

In [2]:
df.head()

   time  temperature_C  vibration_g  current_A system_state
0     0      20.397371     0.709903   1.932482       normal
1     1      19.989382     0.638695   1.995546       normal
2     2      20.718098     0.508945   1.940743       normal
3     3      21.518244     0.402959   1.999154       normal
4     4      20.212251     0.604733   1.850520       normal

## Parte 1 — Función para convertir valores

Cree una función llamada `convertir_a_float(valor)` que intente convertir un valor a número decimal.

La función debe retornar:

- El número convertido, si la conversión es posible.
- `None`, si el valor no se puede convertir.

In [3]:
# TODO: cree la función convertir_a_float

def convertir_a_float(valor):
    try:
        return float(valor)
    except:
        return None

# Pruebas sugeridas

print(convertir_a_float("12.5"))
print(convertir_a_float("error"))
print(convertir_a_float(""))
print(convertir_a_float(None))

12.5
None
None
None

## Parte 2 — Función para calcular potencia

Cree una función llamada `calcular_potencia(voltaje, corriente)`.

La función debe:

- Retornar `None` si voltaje o corriente son `None`.
- Retornar `None` si voltaje o corriente son negativos.
- Retornar `voltaje * corriente` en los demás casos.

In [5]:
# TODO: cree la función calcular_potencia

def calcular_potencia(voltaje, corriente):
    if voltaje is None or corriente is None:
        return None

    if voltaje < 0 or corriente < 0:
        return None

    return voltaje * corriente

# Pruebas sugeridas

print(calcular_potencia(12, 2))
print(calcular_potencia(None, 2))
print(calcular_potencia(12, -1))

24
None
None

## Parte 3 — Función para clasificar temperatura

Cree una función llamada `clasificar_temperatura(temp)` con los siguientes criterios:

- Si `temp` es `None`: `"Dato inválido"`
- Si `temp < 40`: `"Normal"`
- Si `40 <= temp < 50`: `"Precaución"`
- Si `temp >= 50`: `"Alerta"`

In [8]:
# TODO: cree la función clasificar_temperatura

def clasificar_temperatura(temp):
    if temp is None:
        return "Dato inválido"
    elif temp < 40:
        return "Normal"
    elif temp < 50:
        return "Precaución"
    else:
        return "Alerta"

# Pruebas sugeridas
print(clasificar_temperatura(35))
print(clasificar_temperatura(40))
print(clasificar_temperatura(52))
print(clasificar_temperatura(50))
print(clasificar_temperatura(None))

Normal
Precaución
Alerta
Alerta
Dato inválido

## Parte 4 — Limpieza y procesamiento de registros

Procese la lista `registros_crudos` y cree una nueva lista llamada `registros_limpios`.

Cada registro limpio debe contener:

- `id`
- `voltaje`
- `corriente`
- `temperatura`
- `potencia`
- `estado_temperatura`

Use las funciones creadas.

In [10]:
# Para este ejercicio, asumiremos un voltaje constante, ya que no está presente en el conjunto de datos original.
df['voltaje_V'] = 12.0

# Convertimos el DataFrame en una lista de diccionarios para simular 'registros_crudos'
registros_crudos = df.to_dict(orient='records') #el orient records se usa para que cada fila del DataFrame se convierte en un diccionario separado, asi se trabaja mas facil

print(f"Total de registros crudos a procesar: {len(registros_crudos)}")

Total de registros crudos a procesar: 1000

In [11]:
registros_limpios = []

for registro_crudo in registros_crudos:
    # Extraer y convertir valores
    id_registro = registro_crudo.get('time')
    voltaje = convertir_a_float(registro_crudo.get('voltaje_V'))
    corriente = convertir_a_float(registro_crudo.get('current_A'))
    temperatura = convertir_a_float(registro_crudo.get('temperature_C'))

    # Calcular potencia
    potencia = calcular_potencia(voltaje, corriente)

    # Clasificar temperatura
    estado_temperatura = clasificar_temperatura(temperatura)

    # Crear el registro limpio
    registro_limpio = {
        'id': id_registro,
        'voltaje': voltaje,
        'corriente': corriente,
        'temperatura': temperatura,
        'potencia': potencia,
        'estado_temperatura': estado_temperatura
    }
    registros_limpios.append(registro_limpio)

print(f"Total de registros limpios creados: {len(registros_limpios)}")

Total de registros limpios creados: 1000

In [12]:
# Mostrar los primeros 5 registros limpios para verificación
print("\nPrimeros 5 registros limpios:")
for i in range(5):
    print(registros_limpios[i])

Primeros 5 registros limpios:
{'id': 0, 'voltaje': 12.0, 'corriente': 1.9324821725025616, 'temperatura': 20.397371322408983, 'potencia': 23.18978607003074, 'estado_temperatura': 'Normal'}
{'id': 1, 'voltaje': 12.0, 'corriente': 1.9955462811794744, 'temperatura': 19.98938189252972, 'potencia': 23.946555374153693, 'estado_temperatura': 'Normal'}
{'id': 2, 'voltaje': 12.0, 'corriente': 1.9407431963770216, 'temperatura': 20.718097501413723, 'potencia': 23.28891835652426, 'estado_temperatura': 'Normal'}
{'id': 3, 'voltaje': 12.0, 'corriente': 1.9991538720301445, 'temperatura': 21.51824391752364, 'potencia': 23.989846464361733, 'estado_temperatura': 'Normal'}
{'id': 4, 'voltaje': 12.0, 'corriente': 1.8505201200913155, 'temperatura': 20.212250770067197, 'potencia': 22.206241441095784, 'estado_temperatura': 'Normal'}

## Parte 5 — Comprensión de listas

Use comprensión de listas para obtener:

1. Lista de potencias válidas.
2. Lista de temperaturas válidas.
3. Lista de motores en alerta.

In [13]:
# TODO: use comprensión de listas

# Lista de potencias válidas
potencias_validas = [registro['potencia'] for registro in registros_limpios if registro['potencia'] is not None]

# Lista de temperaturas válidas
temperaturas_validas = [registro['temperatura'] for registro in registros_limpios if registro['temperatura'] is not None]

# Lista de motores en alerta (registros completos donde el estado de temperatura es 'Alerta')
motores_alerta = [registro for registro in registros_limpios if registro['estado_temperatura'] == 'Alerta']

print(f"Potencias válidas (primeros 5): {potencias_validas[:5]}")
print(f"Temperaturas válidas (primeros 5): {temperaturas_validas[:5]}")
print(f"Cantidad de motores en alerta: {len(motores_alerta)}")
print(f"Primer motor en alerta: {motores_alerta[0] if motores_alerta else 'No hay motores en alerta'}")

Potencias válidas (primeros 5): [23.18978607003074, 23.946555374153693, 23.28891835652426, 23.989846464361733, 22.206241441095784]
Temperaturas válidas (primeros 5): [20.397371322408983, 19.98938189252972, 20.718097501413723, 21.51824391752364, 20.212250770067197]
Cantidad de motores en alerta: 0
Primer motor en alerta: No hay motores en alerta

## Parte 6 — Comprensión de diccionarios

Cree un diccionario llamado `estado_por_motor` donde:

- La clave sea el `id` del motor.
- El valor sea el `estado_temperatura`.

In [15]:
# TODO: cree el diccionario estado_por_motor

estado_por_motor = {registro['id']: registro['estado_temperatura'] for registro in registros_limpios}

print(f"Cantidad de motores en el diccionario: {len(estado_por_motor)}")
print(f"Estado del motor 0: {estado_por_motor[0]}")

Cantidad de motores en el diccionario: 1000
Estado del motor 0: Normal

## Parte 7 — Resumen automático

Cree una función llamada `generar_resumen(registros)` que retorne un diccionario con:

- `total_registros`
- `registros_validos_potencia`
- `potencia_promedio`
- `temperatura_promedio`
- `cantidad_alertas`
- `cantidad_precauciones`
- `cantidad_normales`

In [16]:
# TODO: cree la función generar_resumen

def generar_resumen(registros):
    total_registros = len(registros)

    potencias = [r['potencia'] for r in registros if r['potencia'] is not None]
    temperaturas = [r['temperatura'] for r in registros if r['temperatura'] is not None]

    registros_validos_potencia = len(potencias)
    potencia_promedio = sum(potencias) / len(potencias) if potencias else None
    temperatura_promedio = sum(temperaturas) / len(temperaturas) if temperaturas else None

    cantidad_alertas = len([r for r in registros if r['estado_temperatura'] == 'Alerta'])
    cantidad_precauciones = len([r for r in registros if r['estado_temperatura'] == 'Precaución'])
    cantidad_normales = len([r for r in registros if r['estado_temperatura'] == 'Normal'])

    return {
        'total_registros': total_registros,
        'registros_validos_potencia': registros_validos_potencia,
        'potencia_promedio': potencia_promedio,
        'temperatura_promedio': temperatura_promedio,
        'cantidad_alertas': cantidad_alertas,
        'cantidad_precauciones': cantidad_precauciones,
        'cantidad_normales': cantidad_normales
    }

resumen = generar_resumen(registros_limpios)
resumen

{'total_registros': 1000,
 'registros_validos_potencia': 1000,
 'potencia_promedio': 24.14998358260266,
 'temperatura_promedio': 20.161157833395325,
 'cantidad_alertas': 0,
 'cantidad_precauciones': 0,
 'cantidad_normales': 1000}

## Parte 8 — Visualización como tabla

Convierta `registros_limpios` en un `DataFrame` de Pandas.

In [17]:
import pandas as pd

# TODO: cree un DataFrame llamado df

df = pd.DataFrame(registros_limpios)
df.head()

   id  voltaje  corriente  temperatura   potencia estado_temperatura
0   0     12.0   1.932482    20.397371  23.189786             Normal
1   1     12.0   1.995546    19.989382  23.946555             Normal
2   2     12.0   1.940743    20.718098  23.288918             Normal
3   3     12.0   1.999154    21.518244  23.989846             Normal
4   4     12.0   1.850520    20.212251  22.206241             Normal

In [18]:
from google.colab import sheets
sheet = sheets.InteractiveSheet(df=df)

https://docs.google.com/spreadsheets/d/1I49A8A0hn672POKyW3IULcmsya0TQnvxlZXx-LXZOwM/edit#gid=0

## Parte 9 — Buenas prácticas

Revise su notebook y verifique:

- Los nombres de variables son claros.
- Las funciones tienen una tarea específica.
- El código no está repetido innecesariamente.
- Las celdas están ejecutadas en orden.
- Hay explicaciones en texto.

## Parte 10 — Repositorio inicial en GitHub

Cree un repositorio en GitHub con el nombre:

**analisis-datos-python-apellido-nombre**

Estructura mínima esperada:

```text
analisis-datos-python-apellido-nombre/
│
├── README.md
├── requirements.txt
├── notebooks/
│   ├── semana_02_introduccion.ipynb
│   ├── semana_03_fundamentos_python.ipynb
│   └── semana_04_funciones_modularizacion.ipynb
│
├── data/
│   ├── raw/
│   └── processed/
│
├── src/
│   └── funciones.py
│
└── reports/
    └── figuras/
```

Enlace al repositorio:

Pegue aquí el enlace de su repositorio.

**Enlace al repositorio:**  
https://github.com/kcvillaronga-prog/analisis-datos-python-Villaronga-Karen

## Parte 11 — Reflexión final

Responda:

1. ¿Qué ventaja tuvo usar funciones en el procesamiento de los registros?
2. ¿Por qué es importante manejar errores antes de analizar datos?
3. ¿Qué función del taller considera más útil?
4. ¿Qué elemento del repositorio ayuda más a la reproducibilidad?


**Respuesta:**

- Usar funciones evitó repetir el mismo código para cada registro; cada función (convertir, calcular potencia, clasificar temperatura) se prueba una sola vez y luego se reutiliza para todo el dataset, lo que reduce errores y facilita corregir algo en un solo lugar si hace falta.
- Manejar errores antes de analizar los datos es importante porque un dato inválido o vacío puede romper todo el cálculo (por ejemplo, sumar `None` con un número). Al validar primero, el resto del análisis puede correr sin interrumpirse y sin resultados falsos.
- La función `convertir_a_float` me pareció la más útil, porque sin ella ningún otro cálculo (potencia, clasificación) podría hacerse de forma segura con los datos crudos.
- El archivo `README.md` es muy útil en la reproducibilidad porque explica qué contiene el repositorio y qué herramientas se necesitan para ejecutarlo, sin depender de que alguien más recuerde cómo estaba organizado el proyecto.